name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
      - run: ./gradlew build
      - run: ./ion-test-driver-run version

  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/is-valid-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          project_version: ${{ env.PROJECT_VERSION }}
          repo: amzn/ion-java
          fail_if_invalid: true

  report-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew check
      - uses: codecov/codecov-action@v1
        with:
          file: build/reports/jacoco/test/jacocoTestReport.xml
